#we use node
language: node_js

#we add the node 12 environment
node_js:
  - lts/dubnium

#we need google-chrome for testing
addons:
  chrome: stable
  sonarcloud:
    organization: "rubensa"

#cache node libraries
cache:
  directories:
     - ./node_modules

#install project libraries
install:
  - npm install

script:
  #run test with code coverage report in headless mode
  - npm run test-ci --  --code-coverage
  - npm run e2e-ci
  #inspect code with the SonarQube Scanner
  - sonar-scanner -Dsonar.projectKey=rubensa_reservas-client
  #build for GitHub Pages
  - ng build --base-href "https://rubensa.eu.org/reservas-client/"

after_success:
  # Set CODECOV_TOKEN in travis-ci.org settings page of your repository, as a secure variable
  - bash <(curl -s https://codecov.io/bash)

#deploy on GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_OAUTH_TOKEN # Set in travis-ci.org settings page of your repository, as a secure variable
  local_dir: dist/reservas
  on:
    branch: master