#we use node
language: node_js

#we add the node 12 environment
node_js:
  - lts/dubnium

#we need google-chrome for testing
addons:
  chrome: stable
  sonarcloud:
    organization: "rubensa"
    token:
      secure: $SONAR_TOKEN

#cache node libraries
cache:
  directories:
     - ./node_modules

#install project libraries
install:
  - npm install

#run test
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  #enable code coverage reports
  - ng test --no-watch --code-coverage --no-progress --browsers=ChromeHeadlessCI
  #inspect code with the SonarQube Scanner
  - sonar-scanner -Dsonar.projectKey=rubensa_reservas-client
  #build for GitHub Pages
  - ng build --base-href "https://rubensa.eu.org/reservas-client/"

after_success:
  # Set CODECOV_TOKEN in travis-ci.org settings page of your repository, as a secure variable
  - bash <(curl -s https://codecov.io/bash)

#deploy on GitHub Pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_OAUTH_TOKEN # Set in travis-ci.org settings page of your repository, as a secure variable
  local_dir: dist/reservas
  on:
    branch: master